In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv("E:\dataset_folder\Auto_training_dataset.csv")

In [3]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0  18.0          8         307.0        130    3504          12.0    70   
1  15.0          8         350.0        165    3693          11.5    70   
2  18.0          8         318.0        150    3436          11.0    70   
3  16.0          8         304.0        150    3433          12.0    70   
4  17.0          8         302.0        140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [4]:
df.tail()

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin             name  
392       1  ford mustang gl  
393       2        vw pickup  
394       1    dodge rampage  
395       1      ford ranger  
396       1       chevy s-10

In [5]:
df.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  397.000000  397.000000    397.000000   397.000000    397.000000   
mean    23.515869    5.458438    193.532746  2970.261965     15.555668   
std      7.825804    1.701577    104.379583   847.904119      2.749995   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.000000  2223.000000     13.800000   
50%     23.000000    4.000000    146.000000  2800.000000     15.500000   
75%     29.000000    8.000000    262.000000  3609.000000     17.100000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

             year      origin  
count  397.000000  397.000000  
mean    75.994962    1.574307  
std      3.690005    0.802549  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [6]:
df.shape

(397, 9)

In [7]:
df = df.drop_duplicates()
df


mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0    18.0          8         307.0        130    3504          12.0    70   
1    15.0          8         350.0        165    3693          11.5    70   
2    18.0          8         318.0        150    3436          11.0    70   
3    16.0          8         304.0        150    3433          12.0    70   
4    17.0          8         302.0        140    3449          10.5    70   
..    ...        ...           ...        ...     ...           ...   ...   
392  27.0          4         140.0         86    2790          15.6    82   
393  44.0          4          97.0         52    2130          24.6    82   
394  32.0          4         135.0         84    2295          11.6    82   
395  28.0          4         120.0         79    2625          18.6    82   
396  31.0          4         119.0         82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

In [8]:
df.replace("?", np.nan, inplace = True)
df.head(100)

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0   18.0          8         307.0        130    3504          12.0    70   
1   15.0          8         350.0        165    3693          11.5    70   
2   18.0          8         318.0        150    3436          11.0    70   
3   16.0          8         304.0        150    3433          12.0    70   
4   17.0          8         302.0        140    3449          10.5    70   
..   ...        ...           ...        ...     ...           ...   ...   
95  12.0          8         455.0        225    4951          11.0    73   
96  13.0          8         360.0        175    3821          11.0    73   
97  18.0          6         225.0        105    3121          16.5    73   
98  16.0          6         250.0        100    3278          18.0    73   
99  18.0          6         232.0        100    2945          16.0    73   

    origin                       name  
0        1  chevrolet chevelle malibu  
1        1          buick skylark 320  
2        1         plymouth satellite  
3        1              amc rebel sst  
4        1                ford torino  
..     ...                        ...  
95       1   buick electra 225 custom  
96       1    amc ambassador brougham  
97       1           plymouth valiant  
98       1      chevrolet nova custom  
99       1                 amc hornet  

[100 rows x 9 columns]

In [9]:
print("Total Null-values in :\n" , df.isnull().sum())

Total Null-values in :
 mpg             0
cylinders       0
displacement    0
horsepower      5
weight          0
acceleration    0
year            0
origin          0
name            0
dtype: int64


In [10]:
df.dropna(how='any',subset=['horsepower'],inplace=True) 

In [11]:
x = df[['mpg','cylinders','horsepower','weight','year','acceleration','displacement']].values
y = df['origin'].values

In [12]:
from sklearn.impute import SimpleImputer
help(SimpleImputer)
print(x[:,1:3])

Help on class SimpleImputer in module sklearn.impute._base:

class SimpleImputer(_BaseImputer)
 |  SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, verbose=0, copy=True, add_indicator=False)
 |  
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <impute>`.
 |  
 |  .. versionadded:: 0.20
 |     `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
 |     estimator which is now removed.
 |  
 |  Parameters
 |  ----------
 |  missing_values : int, float, str, np.nan or None, default=np.nan
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For pandas' dataframes with
 |      nullable integer dtypes with missing values, `missing_values`
 |      should be set to `np.nan`, since `pd.NA` will be converted to `np.nan`.
 |  
 |  strategy : string, default='mean'
 |      The imputation strategy.
 |  
 |      - If "mean", then replace missing values u

In [13]:
imputer = SimpleImputer(missing_values=np.nan,strategy= 'mean')
imputer.fit(x[1:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [14]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_test , y_train = train_test_split(x,y,test_size=0.2,random_state=2)

In [15]:
print(y_train)
print(x_test)
print(y_train)
print(y_test)

[1 3 1 3 2 2 1 1 1 1 1 1 1 1 2 1 2 1 2 1 1 3 2 1 2 1 1 1 1 1 1 1 1 1 2 2 1
 3 1 1 1 1 2 1 1 1 2 1 1 1 1 3 1 1 1 1 1 1 1 1 1 3 1 1 2 1 1 1 3 2 1 1 3 1
 1 1 1 1 2]
[[26.0 4.0 70.0 1955 71 20.5 91.0]
 [19.0 3.0 97.0 2330 72 13.5 70.0]
 [24.3 4.0 90.0 3003 80 20.1 151.0]
 [33.0 4.0 53.0 1795 75 17.5 91.0]
 [41.5 4.0 76.0 2144 80 14.7 98.0]
 [43.4 4.0 48.0 2335 80 23.7 90.0]
 [25.0 6.0 110.0 2945 82 16.4 181.0]
 [21.0 4.0 72.0 2401 73 19.5 140.0]
 [18.5 6.0 110.0 3645 76 16.2 250.0]
 [18.0 8.0 150.0 3436 70 11.0 318.0]
 [24.5 4.0 60.0 2164 76 22.1 98.0]
 [18.0 6.0 105.0 3459 75 16.0 250.0]
 [34.7 4.0 63.0 2215 81 14.9 105.0]
 [18.0 6.0 97.0 2984 75 14.5 171.0]
 [25.0 4.0 115.0 2671 75 13.5 121.0]
 [19.0 6.0 100.0 2634 71 13.0 232.0]
 [29.0 4.0 70.0 1937 75 14.0 90.0]
 [13.0 8.0 130.0 3870 76 15.0 302.0]
 [26.0 4.0 75.0 2246 74 14.0 116.0]
 [20.0 8.0 110.0 3221 75 13.5 262.0]
 [13.0 8.0 190.0 4422 72 12.5 400.0]
 [37.0 4.0 92.0 2434 80 15.0 119.0]
 [25.0 4.0 87.0 2672 70 17.5 110.0]
 [10.0 8

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:,4:])

In [18]:
print(x_train)

[[17.5 6.0 95.0 ... -0.012971469468764197 0.8252835150191139
  0.5989080417175068]
 [25.0 4.0 92.0 ... -0.012971469468764197 -0.21775442230036082
  -0.5180697456834271]
 [16.0 8.0 150.0 ... -1.6369994469582125 -1.2607923596198356
  1.03434006053482]
 ...
 [13.0 8.0 130.0 ... -1.0956567877950631 -0.5414558511236461
  1.0627378008924708]
 [22.0 6.0 95.0 ... -1.6369994469582125 -0.0019534697515041304
  0.03095323456448953]
 [23.0 4.0 78.0 ... -0.2836427990503389 1.07705129299278
  -0.5180697456834271]]
