In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt

In [2]:
dataset = pd.read_csv("E:\dataset_folder\sample_data.csv")

In [3]:
print(dataset)

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
13      NaN  44.0  45000.0       Yes
14   France  47.0  78000.0       NaN
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
17    Spain  27.0  48000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
22  Germany  50.0  83000.0        No
23   France  37.0  67000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
2

In [4]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Nigeria  18.0  15000.0        No

In [5]:
dataset.tail()

Country   Age   Salary Purchased
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
26   France  37.0  67000.0       Yes
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No

In [6]:
dataset.describe()

Age        Salary
count  27.000000     28.000000
mean   36.925926  53642.857143
std     8.757089  19216.532785
min    18.000000  15000.000000
25%    30.000000  44750.000000
50%    37.000000  53000.000000
75%    44.000000  67000.000000
max    50.000000  83000.000000

## Data Preprocessing

In [7]:
dataset = dataset.drop_duplicates()
print(dataset)

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
13      NaN  44.0  45000.0       Yes
14   France  47.0  78000.0       NaN
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No


In [8]:
dataset.isnull().head()

Country    Age  Salary  Purchased
0    False  False   False      False
1    False  False   False      False
2    False  False   False      False
3    False  False   False      False
4    False  False   False      False

In [9]:
print("Total Null-values in :" , 
      dataset.isnull().sum())

Total Null-values is : Country      1
Age          2
Salary       1
Purchased    1
dtype: int64


In [10]:
dataset.dropna(how='any',subset=['Country','Purchased'],inplace=True) 
#inplace = True --> we are doing in the same dataset
#any --> removing that rows of country and purchased where NaN are available

In [11]:
print(dataset)

    Country   Age   Salary Purchased
0    France  44.0  72000.0        No
1     Spain  27.0  48000.0       Yes
2   Germany  30.0  54000.0        No
3     Spain  38.0  61000.0        No
4   Nigeria  18.0  15000.0        No
5   Germany  40.0      NaN       Yes
6    France  35.0  58000.0       Yes
7     Spain   NaN  52000.0        No
8    France  48.0  79000.0       Yes
9   Germany  50.0  83000.0        No
10   France  37.0  67000.0       Yes
11  Nigeria  50.0  60000.0       Yes
12   France  22.0  30000.0        No
15  Nigeria  35.0  43000.0       Yes
16    Spain  34.0  44000.0       Yes
18    Spain  33.0  48000.0       Yes
19  Nigeria  29.0  77000.0       Yes
20    Spain   NaN  57000.0       Yes
21   France  44.0  48000.0       Yes
24   France  37.0  23000.0       Yes
25  Germany  45.0  50000.0        No
27  Nigeria  30.0  30000.0       Yes
28  Nigeria  29.0  15000.0        No


In [12]:
x = dataset[['Country','Age','Salary']].values
y = dataset['Purchased'].values
# print(x,y)

In [13]:
from sklearn.impute import SimpleImputer
help(SimpleImputer)
print(x[:,1:3])

Help on class SimpleImputer in module sklearn.impute._base:

class SimpleImputer(_BaseImputer)
 |  SimpleImputer(*, missing_values=nan, strategy='mean', fill_value=None, verbose=0, copy=True, add_indicator=False)
 |  
 |  Imputation transformer for completing missing values.
 |  
 |  Read more in the :ref:`User Guide <impute>`.
 |  
 |  .. versionadded:: 0.20
 |     `SimpleImputer` replaces the previous `sklearn.preprocessing.Imputer`
 |     estimator which is now removed.
 |  
 |  Parameters
 |  ----------
 |  missing_values : int, float, str, np.nan or None, default=np.nan
 |      The placeholder for the missing values. All occurrences of
 |      `missing_values` will be imputed. For pandas' dataframes with
 |      nullable integer dtypes with missing values, `missing_values`
 |      should be set to `np.nan`, since `pd.NA` will be converted to `np.nan`.
 |  
 |  strategy : string, default='mean'
 |      The imputation strategy.
 |  
 |      - If "mean", then replace missing values u

In [14]:
imputer = SimpleImputer(missing_values=np.nan,strategy= 'mean')
imputer.fit(x[1:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [16]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_test , y_train = train_test_split(x,y,test_size=0.2,random_state=2)

In [18]:
print(y_train)
print(x_test)
print(y_train)
print(y_test)

['No' 'No' 'Yes' 'Yes' 'Yes']
[[0.0 1.0 0.0 0.0 45.0 50000.0]
 [1.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 0.0 30.0 30000.0]
 [1.0 0.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 0.0 1.0 34.0 44000.0]]
['No' 'No' 'Yes' 'Yes' 'Yes']
['Yes' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:,4:])

In [20]:
print(x_train)

[[0.0 0.0 1.0 0.0 -0.7415044996645017 1.3543933494714646]
 [0.0 0.0 0.0 1.0 0.2931529417278258 0.5355837755406954]
 [1.0 0.0 0.0 0.0 -1.5462380651918677 -1.0508597739501704]
 [0.0 1.0 0.0 0.0 1.6726961969175957 1.6614469396955032]
 [0.0 0.0 1.0 0.0 -2.0060858169217908 -1.8184937495102667]
 [1.0 0.0 0.0 0.0 0.17819100379534497 0.8426373657647338]
 [0.0 1.0 0.0 0.0 0.5230768175927875 -0.04684327258267934]
 [0.0 0.0 0.0 1.0 0.01149619379324743 0.330881382058003]
 [0.0 0.0 0.0 1.0 -0.9714283755294634 -0.12969900327805478]
 [0.0 1.0 0.0 0.0 -0.6265425617320209 0.17735458694598374]
 [0.0 0.0 0.0 1.0 0.01149619379324743 0.07500339020463756]
 [1.0 0.0 0.0 0.0 0.17819100379534497 -1.409088962544882]
 [1.0 0.0 0.0 0.0 0.9829245693227109 -0.12969900327805478]
 [0.0 0.0 1.0 0.0 1.6726961969175957 0.48440817717002227]
 [0.0 0.0 1.0 0.0 -0.7415044996645017 -1.8184937495102667]
 [0.0 0.0 1.0 0.0 -0.0517328720696167 -0.3855769951314202]
 [0.0 0.0 0.0 1.0 -0.2816567479345784 -0.12969900327805478]
 [1.0